apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-configs
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: homelab
  path: ./infrastructure/configs
  prune: true
  wait: true
  dependsOn:
    - name: infrastructure-controllers
