apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-config
  namespace: ntfy
data:
  server.yml: |
    listen-http: ":80"
    cache-file: /var/cache/ntfy/cache.db
    cache-duration: "12h"
    attachment-cache-dir: /var/cache/ntfy/attachments
    attachment-total-size-limit: "1G"
    attachment-file-size-limit: "15M"
    attachment-expiry-duration: "3h"
    keepalive-interval: "45s"
    log-level: info
