apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium-repo.yaml
  - cilium.yaml
  - csi-nfs-repo.yaml
  - csi-nfs.yaml
  - cert-manager-namespace.yaml
  - cert-manager-repo.yaml
  - cert-manager.yaml
  - external-dns-namespace.yaml
  - external-dns-repo.yaml
  - external-dns.yaml
