apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-router
  namespace: minecraft
  labels:
    app: mc-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-router
  template:
    metadata:
      labels:
        app: mc-router
    spec:
      serviceAccountName: mc-router
      containers:
        - name: mc-router
          image: itzg/mc-router:1.40.1
          args:
            - --in-kube-cluster
          ports:
            - containerPort: 25565
              name: minecraft
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 50m
            limits:
              memory: 64Mi
