apiVersion: v1
kind: Service
metadata:
  name: mc-router
  namespace: minecraft
  annotations:
    tailscale.com/expose: "true"
spec:
  type: LoadBalancer
  selector:
    app: mc-router
  ports:
    - port: 25565
      targetPort: minecraft
      protocol: TCP
      name: minecraft
