apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:gItE2FSSs5Zzkfl09UlPy+ZSljnd9idmiof/5jxpq/JrB+CXlfD/zg==,iv:4D+gpaUkhuuoXmrhXVfeapUzgTBYgtMfgEd3ORIpOsc=,tag:3+b/kLgBLhTsfVtkes1ikg==,type:str]
sops:
    age:
        - recipient: age182t6rrn2ymaqrmf28xln99kyq0uek62g7yp27am766p9k2z6hpascv5qr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UE15SWdFTlcyTGVLbzN6
            L1o4YTJ6K1VWVU13cHhqZ0NGbjNrbkJwcWh3CmR2eU9SdysvaExsWVQzQThJNzQ1
            MXdyKy9ycEp3RWZScWtxSEJaOTRSRmcKLS0tIDBqZHoxT092MnFGbU1BMzEwTTFL
            YkluaXNSNER4R1FPcDZ3OTRPVk9Ta0UKaR5+QbKRNveZHjsRPcU0QE8V04dGuLnu
            TA7MXe9hv6ovcZOIYBItluepArsrcR46Nw3DdcDjV/+ubBQHYFB73g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T10:30:39Z"
    mac: ENC[AES256_GCM,data:oDcFTaR8Zn/yZi+1vxHKQlz6eu6hIBD13jjyOf1P/r1oxqtX1ilYtazHrKA/GcKdgagBIz4jhEa8E58O5zKselftGEZ+nWn7BYL2nzzWLUjyh4KtLW9lmcEvtRhImyEl9EDh2smyyWnwA5O1M0S8e5gKegUo0oLSi2Q4JqKzXkI=,iv:OiGVhGtjolrkXQHj990EW9V4ARrtl2eSdPsMOlLye5U=,tag:Elj2wBYooTOel927qrk9sA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
