apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ahqOXYAMR1VTRSle4XhKWi63YQbD0ZcOFtqEhhMLlAFEF1RPbyWoHA==,iv:TNkyGOpgKmlTSEkc07ejo7R4BtkWpcscy/MsrwhvAs0=,tag:8ttxr3OPRGBI2YDE4dvrkg==,type:str]
sops:
    age:
        - recipient: age1pq1h0332mwzt2w2fze7hslxcdyle0y3rz63pvaew0p2g7dplws6gym5tveygt620yf28jhu6xudtp5q724yevlpgtyeyxvxea3pv54mf673j6actza33s6al4msqryvqzg9hkjgtgx3pjp7gzxyzfetpclhnhjmc3us2dkxv3nflz2vkr7my98hwj7f5jer49ajcuvrc0fqgcay3srlmsk29pxgf9vck22g3hwjhyzussk5avnzgxycgaj6pu2kvdd9h2l3m3fvumeg0m7hseulzh546x2s7umxswczs6733l2ydgpang8y6mx8a34mjvpk2n3r8gsxednswu64mlq6fg3yh0prwrcdskg5cmqtsvp3qfnrrxwz0yf0rz23vw3ylht369jk0vnerpwzgq8q9k6p25jv9rm390pcglx3q6lrzpkz3predl9cxh48j5svss70rxgsy3ucwf4fghcyv8mck2x4wuj5m4grsd743w78zggufgvf2ddwtmrf4gnchdnecudruk74hju8e9ngua6fshp9grcrzw7z0c3vrru3l35g9pu44yqkju8vve2xv478dy2y8heqcj6ucq395h9ss3ek3374e4lxyxjyus638juwzrvrcl0e5yxuwd8qucet8pj8579nsydgk5fngx03u7an6acvnj6ugefh32xse39tcd4y03rktu58lylchwhvr2eryjvcewvmcme8zxuehrjwr3nwmnxunkjqyc2evkls8v9d5rjdqgrx79ddryujz7dcr48uvv6fzc57pcxz0rjz8pytw07sdvh5fgfefjeqxxn386ec44duwx92e3cv3x9v45vxkfm29smsq2fwrfy8834xuwmmpdeyfpz5xctg934jdeccp5s53d23pfsrv6vcy4amefv0yk2qjqgfvy9cejnvvdtjld7t3zmtqv3v02q6gt82qnrvd2mlnt5g2rznf782xr8f5uqk5kqpf0gge52yx4p22pdg9s0c59srk5339vtq8xj25c69w59c20q4x5xp85rqrryeewqfwctp49n920ansmp2qax3vt4quan0u95rhsnndqhmh67m2wcgn9nqmfcqhdt5xz35yxul3drrc5zcv7vqmdjrr34e5tmgynu7x3jk33j854nmc8ds47fjd9kad3fu4c2rznncmmgkk6hqczz47krxh36r9p982lhy8zternzunzagpk30d5xxprs5c9pvtxqtk38z2mrc8upfpynjsgg3y4upsacky96wr2xpgh9msnreccj2aqtjhacxv4rjuzg523gzcjdtukq30qvtl0yv73rkqv662xezsvcqlg6gvy6zdryztsv40n72z99ae59hecmfzfyrgvfu335avkhr9qfduem3mjvc2anqdwcw7lyzugrj63vc7q2sresmf9the23qw62nwp42qq4fhc6jk9k3v27vd54wrldgul265w8wyt0tqu4wwaq6c44zm3dqf9et5lzt9sdff2d57nehr3jn5fk7e9tmt3550e6zr9us98hcy3gqxmqxuuf3p2j66mu4xjus8zcjpdnd23zuvkgtc9aha4v4slwwk6mmjxzz57pk8snkwxamgs0ynds4jypvxxfrwuk9pr3jyyewzscwrptf3j4l4a3ymqk4qezfyrw3xzzhcpysvxqnxtr8z8hwd9razpmjdwfrv3x2gwrhsszdjch6lpz5ux9t5usepe3vry6lwg5w0prg5y2zd645ewtgt3wuprwm8g4hf7qssmmct4legl7t5rcd39825ezuctdkuxxksfv5dsgp3fa2zfjuuype36af8ml5ft7kn25cwvmmh9dq95sv5ggzanej06f8xpjak6fte8ppxlm0vxza4dfep7242lu6v0ce389mhemd7u0e2mvhl0z3xrxku7evjd9h2m8z6xu70v3xre2p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHZlQzQzdlFV
            eDVLK2d4UVUrVFNNbUNLOUhEN1p0OFJsN1ZQcENZVFdYN3N5NytpQTBwY2ltLzMy
            NXNEWjhzZ2xPeDhtTk5Sc05tdVFvUmJvS0U1UExwbGJjckE5ZzFOdndqREpHYlF5
            QUlEbWZUWWlaS2NJQ0dHNHlpY2QydzlxdVc5MEs0NUhKa080RWg4cmdqcVpoZUVv
            dGtNbE9KVGswTzA5U1VrVURvWitibkV4WERhaFhwQkczMUowM0dtMkVZTmZXSTN5
            b1NCd2pDdEFhcEFNV1JpRHpiWHpmZXZkdjFUWlF6NnpFRUlnMFRrWlNjTWFTYVdO
            MnAwN1FVR1pMZ1h1SmZqUE5SYWkvOGhRWmtISkJsblhNS0QrVnNLMTd6cktxNHJ0
            Q2hGZlg4K2FVaUpWZjNjWitiZnVEdkY0RVc2cFpLdlRwVW9HeSttNWZuaFhqWEJl
            M2h3aEhhWmJpb0I4aG9BUVhiUU1CdmZReHZldUd4dGlxbnZOWkgrZ3RGV3Bsek50
            alRTeUluOUR3L1dVN1ZVMHF0aElMZnFVNFQ5QlU5M0hIZjhsYWRVbGV3SWpyS3Yy
            TDlyaG1kdU1aUmRsdXVwMlAzV2p1T1BIbHR0a2pBSnJiVmNTekpSNWdtbnovT1Fz
            QU5WbnM0WlRCOHdwOTZaSGhpQnBvRzBXZEVlUGlTRTBFMjNsd2JXMHNTZUhYQTJL
            cFdOWS82OFZ5Q3pwTU50VGg3UEZ3UUhKelZ2S3o2NkliWDM4U3VodjRqT3hvdTVW
            UzRvUzF3N2JwNnhudFZMU2VSWVZBZFhHVCtFVnpaZEtvVmRaYm9TVEFzUlRWTm9N
            cW45eFcyRWlmSDV0R1pBN2FucVNOdHUrSVNlMkZuMzdQTDNnYXRBRXI0UDdWMlUr
            QXV1N2wyRVFaelBLQ0I3QTNyL2toZlNrV2hxc0xLTEl3RGZHc29YR0h1aHdzL0c2
            TUFtNkdCREZVcFFLTmN5djNzTVZoZ09vRVdJTGxQaktGRFlpdjM1OUxsellFZXl4
            b1VaK2s2Z1Q4OGJQMDZiRkJHeVNNK0hCSTdoaTZmSTlyMW1MejhOcTJ5Um5UVWJ2
            RmM2ZDhNdGVTcm51TFlaT09TVDIxV285Z0d2bDdZbGtxejFydTZkR2F0YU41MjUw
            VEluaWtWc2ljdXZ5b0duZHBQMFlLVUN1UUlQQnJ2U25KSWE2OTdyRTNHV0t0bWRB
            WmF2UEpiaUgwNCtacXIzd1pWb2VvdlFMY0s2MjNRTkJLTHJMMkl4T1JzbmZDWnFG
            MXBNTHNDY2dZNTUweHMxbit2SlhaNStJYnZBbW9JMlNFanV6eFppcSthRUlMZVVu
            TUIyekp5ZFEvMTM2TFo4dDZPQStJMTVFd09UTEFmOWthbjRxM2IvWWRMVTQ5UXQv
            d09MNExhY1NydjB5ZWJEK3JNc1dKNVRyNHFzOE42dWZINUpvbnJ6SytyRFdWVU9I
            K1BlR0kxZ1RKc3U0eHFJSlB6YWR4NlhsNGFCTyt6K2VaYXJpVGw1MVBxUDVvMmxG
            ckZ1Mk9lYW9FYnA2L1UyM04rYThKNmRMbndpMExtRXpsTE9TNzBob3hqT3N1WGx0
            dXQ2Ump3RzU5RW1RbzRFd0tKanBFRGxXcTg2MXNuTm02YWc0dkVmejB3K3JaRE9G
            Q3JSeTU0dkhkUDhJNy9ITm1iVGVuR0JnSUJIeVBuTGpXSzFJTGVqdjJZeTJrZ3dn
            YjdoSng2NVVBc3p5T2k1TzFuWnJUT1k4OUk3WlAxaXVLMzdpcVVOVGNod3RZejVn
            RkdKNnBYNlBIdUQ5Y1BLYmVzVjZ1OCtxUGJ0bjNqUEl1ZzluUCs4TXZkMTlKNzh6
            bEJ5RThDYmFaYm92OXlkN0Q3UWVKekY0UkxocHVYQzIrQW05KzB6cytmNWZvaU9H
            NUVvbVI1UitCRytNeVlaT0xMclVSbUdqSUd3T01wc0tmMGR3ZUFyMXB3THhPQQpa
            WTBXRUJocXNwdWpQRDc0QjNrZ3VNWjQyQWVsMHJVZkRmYnlwODBDR0VNCi0tLSBi
            V0Z4THZCWGhCNE5HOG56QlBlbnlBWndRMndNR3UrQjhoZFNDdGIvRXlJCtYoMfoa
            16o4RBSTtiEzaaN6DuPY+l7fU4ft85BNwubNqV3Pj7XTyx1PEWuM5QqVTlJhuGpv
            QaSLX6tZa/WkWj0=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T09:13:51Z"
    mac: ENC[AES256_GCM,data:g3DxwcB3+ia+/HKsaDWmhxwWsOXKroxdJMcIoUuyATH8Ctv8efNTFYrJwC62BW73k9l3rIcflggRLyyuiLh6PjaAPm1iIDjOUSSwrQnAPO5DE57efflQrvKDT0ShbOSaogUkpOL1RbdiGAEA/3Q/xP0AdDP0qJtps9+Eqfqokms=,iv:DexnoILjqNv0jUDc8tjXXUMQzVzqIk61DOt/4SY0PJQ=,tag:tSKmqlOyxpTsdJdsVwuv/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
