apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium-l2-policy.yaml
  - cilium-ip-pool.yaml
  - cloudflare-api-token.yaml
  - cert-manager-clusterissuer.yaml
  - external-dns-cloudflare-api-token.yaml
